/**
 * Name: Andrew Semchism
 * Date: June 10 2018
 * Description: Title screen for hangman game
 */
package main;

import java.util.logging.Level;
import java.util.logging.Logger;
import org.xml.sax.SAXException;



public class TitleScreen extends javax.swing.JFrame {
    
    
    public TitleScreen() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        one = new javax.swing.JLabel();
        two = new javax.swing.JLabel();
        three = new javax.swing.JLabel();
        four = new javax.swing.JLabel();
        instructions = new javax.swing.JLabel();
        name = new javax.swing.JLabel();
        play = new javax.swing.JButton();
        title = new javax.swing.JLabel();
        backround = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMinimumSize(new java.awt.Dimension(700, 520));
        setResizable(false);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(220, 240, 240));
        jPanel1.setLayout(null);

        one.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        one.setText("1. A random word is chosen from the word bank");
        jPanel1.add(one);
        one.setBounds(10, 30, 310, 40);

        two.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        two.setText("2. The player chooses a letter");
        jPanel1.add(two);
        two.setBounds(10, 60, 310, 40);

        three.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        three.setText("3. If the letter is not in the chosen word, a body part is added to the hangman");
        jPanel1.add(three);
        three.setBounds(10, 90, 490, 40);

        four.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        four.setText("4. If the player guesses the word before the hangman is complete, they win!");
        jPanel1.add(four);
        four.setBounds(10, 120, 440, 40);

        instructions.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        instructions.setText("Instructions:");
        jPanel1.add(instructions);
        instructions.setBounds(10, 0, 130, 30);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(10, 220, 470, 160);

        name.setText("Made by Andrew Semchism");
        getContentPane().add(name);
        name.setBounds(10, 10, 190, 14);

        play.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        play.setForeground(new java.awt.Color(0, 10, 130));
        play.setText("Play!");
        play.setToolTipText("");
        play.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                playActionPerformed(evt);
            }
        });
        getContentPane().add(play);
        play.setBounds(260, 420, 190, 60);

        title.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 75)); // NOI18N
        title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        title.setText("Hangman");
        getContentPane().add(title);
        title.setBounds(0, 10, 700, 91);

        backround.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/backround.jpg"))); // NOI18N
        getContentPane().add(backround);
        backround.setBounds(0, -10, 700, 510);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void playActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_playActionPerformed
        try {
            //changes from the TitleScreen to PlayScreen
            new PlayScreen().setVisible(true);
        } catch (SAXException ex) {
            Logger.getLogger(TitleScreen.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.setVisible(false); // makes TitleScreen invisible
    }//GEN-LAST:event_playActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TitleScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TitleScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TitleScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TitleScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TitleScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel backround;
    private javax.swing.JLabel four;
    private javax.swing.JLabel instructions;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel name;
    private javax.swing.JLabel one;
    private javax.swing.JButton play;
    private javax.swing.JLabel three;
    private javax.swing.JLabel title;
    private javax.swing.JLabel two;
    // End of variables declaration//GEN-END:variables
}
